name: Android build CI

on:
  push:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Build with Gradle
        run: gradle clean assemble
      - name: Find apks
        run: find -name "*.apk"
      - uses: actions/upload-artifact@v2
        with:
          name: apks
          path: "*/build/outputs/apk/*/*.apk"
